### ISSUE TITLE
Add BitBucket support

### ISSUE THREAD

**Issue by peti2001** [codersrank-org/multi_repo_extractor#16]
Implement the `Provider` interface that will return with all the repos (according to the visibility) that are accessible with the given token on BitBucket.

**Comment by jaistudy1996** [comment]
Hi @peti2001 I can work on this issue. Can you please assign this to me?

**Comment by peti2001** [comment]
sure, let me know if you have any question

**Comment by jaistudy1996** [comment]
@peti2001 Can you please review the changes made [here](https://github.com/codersrank-org/multi_repo_extractor/compare/master...jaistudy1996:master).

One thing to note is that there is a possibility that Bitbucket Cloud and Bitbucket Server APIs differ. So, for now, the changes in this are only for Bitbucket Cloud.

**Comment by peti2001** [comment]
@jaistudy1996 can you please send a pull request? It is easier to add comments like that.

I can see you added the username as a new parameter. Do you think it is possible to get the username using the token? It would be great if we can keep the number of parameters as low as possible.

**Comment by jaistudy1996** [comment]
@peti2001 [here](https://github.com/codersrank-org/multi_repo_extractor/pull/17) is the pull request for this issue. I was unable to link the issue and pull request for some reason. 

Bitbucket cloud only supports two types of authentication: OAuth and Basic Auth. I am not sure if codersrank has existing infrastructure for OAuth. If there is then we can avoid username. [Bitbucket OAuth Reference](https://developer.atlassian.com/cloud/bitbucket/oauth-2/)

One more thing that I can see is that cloning of repository might not work properly because for github you can simply add `username:token` where `"username"` is hardcoded whereas for Bitbucket we will need the actual `username`.

**Comment by peti2001** [comment]
@jaistudy1996, thanks I'll have a look at it.

**Comment by peti2001** [comment]
I recommended two things and I added them to the PR #17.

**Comment by peti2001** [comment]
Merged #17
